export enum CampaignStage {
  LEADS = 'Leads',
  QUALIFIED_LEADS = 'Qualified Leads',
  ONBOARDING = 'Onboarding',
  COMING_SOON = 'Coming Soon',
  FUNDRAISING = 'Fundraising',
  FUNDED = 'Funded',
  EARLY_COMPLETE = 'Early Complete', // campaign finished early
  MATERIAL_CHANGE = 'Material Change',
  PENDING_REFUNDS = 'Pending Refunds',
  NOT_FUNDED = 'Not Funded',
  PAYING_YOU = 'Paying You',
  PAID_OFF = 'Paid Off',
  PENDING_PAYMENT = 'Pending Payment',
  DEFAULT = 'Default',
  FULLY_REPAID = 'Fully Repaid',
  SUCCESSFUL_FINALIZING = 'Successful - Finalizing',
  MODIFIED = 'Modified Plan',
  DEFAULTED = 'Defaulted',
  IN_INVESTOR_VOTE = 'In Investor Vote',
}