export enum NorthCapitalStatus {
  FUNDED = 'FUNDED',
  CANCELED = 'CANCELED',
  RETURNED = 'RETURNED',
  SUBMITTED = 'SUBMITTED',
  UNWINDSETTLED = 'UNWINDSETTLED',
  UNWINDPENDING = 'UNWINDPENDING',
  UNWIND_SETTLED = 'UNWIND SETTLED',
  UNWIND_PENDING = 'UNWIND PENDING',
  SETTLED = 'SETTLED',
}
