import * as dotenv from 'dotenv';
dotenv.config();

export default {
  ASANA_PERSONAL_ACCESS_TOKEN: process.env.ASANA_PERSONAL_ACCESS_TOKEN,
  PROJECT_GID: process.env.PROJECT_GID,
  DESTINATION_GID: process.env.DESTINATION_GID,
  THREAD_BANK_APPROVAL_GID: process.env.THREAD_BANK_APPROVAL_GID,
  PRE_AUTH_FORM_ATTACHMENT_GID: process.env.PRE_AUTH_FORM_ATTACHMENT_GID,
  PRE_AUTH_ATTACHMENT_OPTION_GID: process.env.PRE_AUTH_ATTACHMENT_OPTION_GID,
  REFUND_AMOUNT_GID: process.env.REFUND_AMOUNT_GID,
  DEBIT_AUTHORIZATION_ID: process.env.DEBIT_AUTHORIZATION_ID,
  DWOLLA_OPTION_GID: process.env.DWOLLA_OPTION_GID,
  ASANA_WEBHOOK_SECRET: process.env.ASANA_WEBHOOK_SECRET
};
