import * as dotenv from 'dotenv';
dotenv.config();

export default {
  dwolla: {
    APP_KEY: process.env.DWOLLA_APP_KEY,
    APP_SECRET: process.env.DWOLLA_APP_SECRET,
    ENVIRONMENT: process.env.DWOLLA_APP_ENVIRONMENT,
    BASE_URL: process.env.DWOLLA_BASE_URL || 'https://api-sandbox.dwolla.com',
    WEBHOOK_SECRET: process.env.DWOLLA_WEB_HOOK_SECRET,
    HONEYCOMB_HOLDINGS_FUNDING_SOURCE: process.env.HONEYCOMB_HOLDINGS_FUNDING_SOURCE,
    BUSINESS_TRANSACTION_MAX: process.env.BUSINESS_TRANSACTION_MAX || 10000,
    INIVIDUAL_TRANSACTION_MAX: process.env.INIVIDUAL_TRANSACTION_MAX || 5000,
    SAME_DAY_ACH_CLIENT: process.env.SAME_DAY_ACH_CLIENT,
    DWOLLA_RE_INVESTMENT_ID: process.env.DWOLLA_RE_INVESTMENT_ID,
    DWOLLA_RE_INVESTMENT_ID_FIRST_CITIZEN:
      process.env.DWOLLA_RE_INVESTMENT_ID_FIRST_CITIZEN,
    DWOLLA_RE_INVESTMENT_ID_THREAD_BANK: process.env.DWOLLA_RE_INVESTMENT_ID_THREAD_BANK,  
    DWOLLA_HONEYCOMB_WALLET_ID: process.env.DWOLLA_HONEYCOMB_WALLET_ID,
    DWOLLA_HONEYCOMB_THREAD_BANK: process.env.DWOLLA_HONEYCOMB_THREAD_BANK,
    DWOLLA_HONEYCOMB_CUSTODY_ACCOUNT: process.env.DWOLLA_HONEYCOMB_CUSTODY_ACCOUNT,
  },
};
