import * as dotenv from 'dotenv';
dotenv.config();

export default {
  ORIGIN_NAME: process.env.NACHA_ORIGIN_NAME,
  DESTINATION_NAME: process.env.NACHA_DESTINATION_NAME,
  ORIGIN_ROUTING_NUMBER: process.env.NACHA_ORIGIN_ROUTING_NUMBER,
  DESTINATION_ROUTING_NUMBER: process.env.NACHA_DESTINATION_ROUTING_NUMBER,
  REFERENCE_CODE: process.env.NACHA_REFERENCE_CODE,
  ORIGIN_IDENTIFICATION: process.env.NACHA_ORIGIN_IDENTIFICATION,
  ORIGIN_DFI: process.env.NACHA_ORIGIN_DFI,
  DESTINATION_ACCOUNT_NUMBER: process.env.NACHA_DESTINATION_ACCOUNT_NUMBER,
};
