version: '3.3'
services:
  api-server:
    build:
      context: ../../
      dockerfile: ops/docker/api-server/dev/Dockerfile
    hostname: api-server
    ports:
      - ${API_PORT}:${API_PORT}
    environment:
      - NODE_ENV=${NODE_ENV}
      - APP_NAME=${APP_NAME}
      - PORT=${API_PORT}
      - SECRET=${SECRET}
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_DIALECT=${DB_DIALECT}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    networks:
      - honeycomb-api
    volumes:
      - ../../:/honeycombs-api
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    restart: always
    command: ['--default-authentication-plugin=mysql_native_password']
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_HOST=%
    ports:
      - '3306:3306'
    expose:
      - '3306'
    networks:
      - honeycomb-api
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    networks:
      - honeycomb-api
volumes:
  honeycomb-db:
networks:
  honeycomb-api: ~
